name: CCDA parsing run workflow
run-name: ${{ github.actor }} is doing a test run of the CCDA parsing
on: [push]
jobs:
    Just-Run:
        runs-on: ubuntu-latest
        steps:
          - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
          - name: Check out repository code
            uses: actions/checkout@v4
          - run: echo "ðŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
          - run: echo "ðŸ–¥ï¸ The workflow is now ready to test your code on the runner."
          - name: List files in the repository
            run: |
              ls ${{ github.workspace }}
          - run: echo "ðŸ This job's status is ${{ job.status }}."
          - name: Display Python Version
            run: python -c "import sys; print(sys.version)"
          - name: run main.py
            run: |
                python3 main.py > todays_output
          - name: diff output
            run: |
                diff todays_output tests/expected_output
